language: csharp
solution: Fluent-State-Machine.sln
 
install:
  - nuget restore Fluent-State-Machine.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
 
script:
  - xbuild /p:Configuration=Debug Fluent-State-Machine.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.exe ./Tests/bin/Debug/Fluent-State-Machine.Tests.dll

group: stable
dist: xenial
os: linux
